  language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "12.3.1"
deploy:
  provider: script
  github-token: $GITHUB_TOKEN
  script: cd docs/ && yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: master